# Generated by Django 4.1.7 on 2023-03-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='user',
            new_name='video_gallery',
        ),
    ]
